# Shallow Neural Network in Keras

Build a shallow neural network to classify MNIST digits

#### Load dependencies

In [1]:
import keras
from keras.datasets import mnist
from keras.models import Sequential
from keras.layers import Dense
from keras.optimizers import SGD

Using TensorFlow backend.


#### Load data

In [2]:
(X_train, y_train), (X_test, y_test) = mnist.load_data()

In [3]:
X_train.shape

(60000, 28, 28)

In [4]:
y_train.shape

(60000,)

In [5]:
y_train[0:100]

array([5, 0, 4, 1, 9, 2, 1, 3, 1, 4, 3, 5, 3, 6, 1, 7, 2, 8, 6, 9, 4, 0,
       9, 1, 1, 2, 4, 3, 2, 7, 3, 8, 6, 9, 0, 5, 6, 0, 7, 6, 1, 8, 7, 9,
       3, 9, 8, 5, 9, 3, 3, 0, 7, 4, 9, 8, 0, 9, 4, 1, 4, 4, 6, 0, 4, 5,
       6, 1, 0, 0, 1, 7, 1, 6, 3, 0, 2, 1, 1, 7, 9, 0, 2, 6, 7, 8, 3, 9,
       0, 4, 6, 7, 4, 6, 8, 0, 7, 8, 3, 1], dtype=uint8)

In [6]:
X_test.shape

(10000, 28, 28)

In [7]:
X_test[0]

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  

In [8]:
y_test.shape

(10000,)

In [9]:
y_test[0]

7

#### Preprocess data

In [10]:
X_train = X_train.reshape(60000, 784).astype('float32')
X_test = X_test.reshape(10000, 784).astype('float32')

In [11]:
X_train /= 254
X_test /= 254

In [12]:
X_test[0]

array([0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.     

In [13]:
n_classes = 10
y_train = keras.utils.to_categorical(y_train, n_classes)
y_test = keras.utils.to_categorical(y_test, n_classes)

In [14]:
y_test[0]

array([0., 0., 0., 0., 0., 0., 0., 1., 0., 0.], dtype=float32)

#### Design neural network architecture

In [15]:
model = Sequential()
model.add(Dense(64, activation='sigmoid', input_shape=(784,)))
model.add(Dense(10, activation='softmax'))

In [16]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 64)                50240     
_________________________________________________________________
dense_2 (Dense)              (None, 10)                650       
Total params: 50,890
Trainable params: 50,890
Non-trainable params: 0
_________________________________________________________________


In [17]:
(64*784)

50176

In [18]:
(64*784)+64

50240

In [19]:
(10*64)+10

650

#### Configure model

In [20]:
model.compile(loss='mean_squared_error', optimizer=SGD(lr=0.01), metrics=['accuracy'])

#### Train!

In [21]:
model.fit(X_train, y_train, batch_size=128, epochs=200, verbose=1, validation_data=(X_test, y_test))

Train on 60000 samples, validate on 10000 samples
Epoch 1/200
60000/60000 [==============================] - 1s 20us/step - loss: 0.0928 - acc: 0.1188 - val_loss: 0.0917 - val_acc: 0.1322
Epoch 2/200
60000/60000 [==============================] - 1s 19us/step - loss: 0.0912 - acc: 0.1512 - val_loss: 0.0907 - val_acc: 0.1844
Epoch 3/200
60000/60000 [==============================] - 1s 18us/step - loss: 0.0904 - acc: 0.2048 - val_loss: 0.0900 - val_acc: 0.2241
Epoch 4/200
60000/60000 [==============================] - 1s 18us/step - loss: 0.0898 - acc: 0.2285 - val_loss: 0.0895 - val_acc: 0.2347
Epoch 5/200
60000/60000 [==============================] - 1s 19us/step - loss: 0.0893 - acc: 0.2361 - val_loss: 0.0890 - val_acc: 0.2407
Epoch 6/200
60000/60000 [==============================] - 1s 20us/step - loss: 0.0889 - acc: 0.2423 - val_loss: 0.0886 - val_acc: 0.2520
Epoch 7/200
60000/60000 [==============================] - 1s 19us/step - loss: 0.0885 - acc: 0.2581 - val_loss: 0.0882 - 

60000/60000 [==============================] - 1s 19us/step - loss: 0.0661 - acc: 0.5532 - val_loss: 0.0655 - val_acc: 0.5646
Epoch 60/200
60000/60000 [==============================] - 1s 18us/step - loss: 0.0657 - acc: 0.5575 - val_loss: 0.0650 - val_acc: 0.5690
Epoch 61/200
60000/60000 [==============================] - 1s 18us/step - loss: 0.0653 - acc: 0.5632 - val_loss: 0.0646 - val_acc: 0.5744
Epoch 62/200
60000/60000 [==============================] - 1s 19us/step - loss: 0.0648 - acc: 0.5691 - val_loss: 0.0642 - val_acc: 0.5805
Epoch 63/200
60000/60000 [==============================] - 1s 22us/step - loss: 0.0644 - acc: 0.5748 - val_loss: 0.0637 - val_acc: 0.5851
Epoch 64/200
60000/60000 [==============================] - 1s 19us/step - loss: 0.0640 - acc: 0.5800 - val_loss: 0.0633 - val_acc: 0.5906
Epoch 65/200
60000/60000 [==============================] - 1s 19us/step - loss: 0.0636 - acc: 0.5857 - val_loss: 0.0629 - val_acc: 0.5956
Epoch 66/200
60000/60000 [==============

Epoch 118/200
60000/60000 [==============================] - 1s 18us/step - loss: 0.0435 - acc: 0.7788 - val_loss: 0.0424 - val_acc: 0.7947
Epoch 119/200
60000/60000 [==============================] - 1s 18us/step - loss: 0.0432 - acc: 0.7803 - val_loss: 0.0421 - val_acc: 0.7966
Epoch 120/200
60000/60000 [==============================] - 1s 18us/step - loss: 0.0429 - acc: 0.7817 - val_loss: 0.0418 - val_acc: 0.7985
Epoch 121/200
60000/60000 [==============================] - 1s 18us/step - loss: 0.0426 - acc: 0.7830 - val_loss: 0.0415 - val_acc: 0.8000
Epoch 122/200
60000/60000 [==============================] - 1s 18us/step - loss: 0.0423 - acc: 0.7847 - val_loss: 0.0412 - val_acc: 0.8020
Epoch 123/200
60000/60000 [==============================] - 1s 18us/step - loss: 0.0420 - acc: 0.7863 - val_loss: 0.0410 - val_acc: 0.8037
Epoch 124/200
60000/60000 [==============================] - 1s 19us/step - loss: 0.0417 - acc: 0.7882 - val_loss: 0.0407 - val_acc: 0.8047
Epoch 125/200
60000/

60000/60000 [==============================] - 1s 19us/step - loss: 0.0309 - acc: 0.8465 - val_loss: 0.0299 - val_acc: 0.8567
Epoch 177/200
60000/60000 [==============================] - 1s 18us/step - loss: 0.0308 - acc: 0.8470 - val_loss: 0.0297 - val_acc: 0.8571
Epoch 178/200
60000/60000 [==============================] - 1s 19us/step - loss: 0.0307 - acc: 0.8477 - val_loss: 0.0296 - val_acc: 0.8575
Epoch 179/200
60000/60000 [==============================] - 1s 19us/step - loss: 0.0305 - acc: 0.8480 - val_loss: 0.0295 - val_acc: 0.8584
Epoch 180/200
60000/60000 [==============================] - 1s 19us/step - loss: 0.0304 - acc: 0.8486 - val_loss: 0.0293 - val_acc: 0.8590
Epoch 181/200
60000/60000 [==============================] - 1s 18us/step - loss: 0.0302 - acc: 0.8491 - val_loss: 0.0292 - val_acc: 0.8592
Epoch 182/200
60000/60000 [==============================] - 1s 18us/step - loss: 0.0301 - acc: 0.8496 - val_loss: 0.0290 - val_acc: 0.8596
Epoch 183/200
60000/60000 [=======

In [22]:
model.evaluate(X_test, y_test)

10000/10000 [==============================] - 0s 40us/step


[0.026870425912737847, 0.8657]