# Shallow Neural Network in Keras

Build a shallow neural network to classify MNIST digits

#### Load dependencies

In [1]:
import keras
from keras.datasets import mnist
from keras.models import Sequential
from keras.layers import Dense
from keras.optimizers import SGD

Using TensorFlow backend.


#### Load data

In [2]:
(X_train, y_train), (X_test, y_test) = mnist.load_data()

In [3]:
X_train.shape

(60000, 28, 28)

In [4]:
y_train.shape

(60000,)

In [5]:
y_train[0:12]

array([5, 0, 4, 1, 9, 2, 1, 3, 1, 4, 3, 5], dtype=uint8)

In [6]:
X_test.shape

(10000, 28, 28)

In [7]:
X_test[0]

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  

In [8]:
y_test.shape

(10000,)

In [9]:
y_test[0]

7

#### Preprocess data

In [10]:
X_train = X_train.reshape(60000, 784).astype('float32')
X_test = X_test.reshape(10000, 784).astype('float32')

In [11]:
X_train /= 255
X_test /= 255

In [12]:
X_test[0]

array([0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.     

In [13]:
n_classes = 10
y_train = keras.utils.to_categorical(y_train, n_classes)
y_test = keras.utils.to_categorical(y_test, n_classes)

In [14]:
y_test[0]

array([0., 0., 0., 0., 0., 0., 0., 1., 0., 0.], dtype=float32)

#### Design neural network architecture

In [15]:
model = Sequential()
model.add(Dense(64, activation='sigmoid', input_shape=(784,)))
model.add(Dense(10, activation='softmax'))

In [16]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 64)                50240     
_________________________________________________________________
dense_2 (Dense)              (None, 10)                650       
Total params: 50,890
Trainable params: 50,890
Non-trainable params: 0
_________________________________________________________________


In [17]:
(64*784)

50176

In [18]:
(64*784)+64

50240

In [19]:
(10*64)+10

650

#### Configure model

In [20]:
model.compile(loss='mean_squared_error', optimizer=SGD(lr=0.01), metrics=['accuracy'])

#### Train!

In [21]:
model.fit(X_train, y_train, batch_size=128, epochs=200, verbose=1, validation_data=(X_test, y_test))

Train on 60000 samples, validate on 10000 samples
Epoch 1/200
60000/60000 [==============================] - 1s 11us/step - loss: 0.0950 - acc: 0.1063 - val_loss: 0.0936 - val_acc: 0.1085
Epoch 2/200
60000/60000 [==============================] - 1s 10us/step - loss: 0.0928 - acc: 0.1223 - val_loss: 0.0921 - val_acc: 0.1321
Epoch 3/200
60000/60000 [==============================] - 1s 10us/step - loss: 0.0916 - acc: 0.1549 - val_loss: 0.0912 - val_acc: 0.1668
Epoch 4/200
60000/60000 [==============================] - 1s 10us/step - loss: 0.0908 - acc: 0.1841 - val_loss: 0.0905 - val_acc: 0.1868
Epoch 5/200
60000/60000 [==============================] - 1s 10us/step - loss: 0.0903 - acc: 0.1996 - val_loss: 0.0900 - val_acc: 0.1993
Epoch 6/200
60000/60000 [==============================] - 1s 9us/step - loss: 0.0898 - acc: 0.2090 - val_loss: 0.0895 - val_acc: 0.2133
Epoch 7/200
60000/60000 [==============================] - 1s 10us/step - loss: 0.0894 - acc: 0.2245 - val_loss: 0.0891 - v

60000/60000 [==============================] - 1s 10us/step - loss: 0.0684 - acc: 0.6154 - val_loss: 0.0676 - val_acc: 0.6260
Epoch 60/200
60000/60000 [==============================] - 1s 10us/step - loss: 0.0679 - acc: 0.6191 - val_loss: 0.0672 - val_acc: 0.6299
Epoch 61/200
60000/60000 [==============================] - 1s 10us/step - loss: 0.0675 - acc: 0.6234 - val_loss: 0.0667 - val_acc: 0.6341
Epoch 62/200
60000/60000 [==============================] - 1s 10us/step - loss: 0.0670 - acc: 0.6274 - val_loss: 0.0663 - val_acc: 0.6375
Epoch 63/200
60000/60000 [==============================] - 1s 10us/step - loss: 0.0666 - acc: 0.6315 - val_loss: 0.0658 - val_acc: 0.6424
Epoch 64/200
60000/60000 [==============================] - 1s 10us/step - loss: 0.0661 - acc: 0.6345 - val_loss: 0.0653 - val_acc: 0.6466
Epoch 65/200
60000/60000 [==============================] - 1s 10us/step - loss: 0.0657 - acc: 0.6367 - val_loss: 0.0649 - val_acc: 0.6489
Epoch 66/200
60000/60000 [==============

Epoch 118/200
60000/60000 [==============================] - 1s 10us/step - loss: 0.0438 - acc: 0.7912 - val_loss: 0.0427 - val_acc: 0.8054
Epoch 119/200
60000/60000 [==============================] - 1s 10us/step - loss: 0.0435 - acc: 0.7936 - val_loss: 0.0424 - val_acc: 0.8071
Epoch 120/200
60000/60000 [==============================] - 1s 9us/step - loss: 0.0432 - acc: 0.7953 - val_loss: 0.0421 - val_acc: 0.8086
Epoch 121/200
60000/60000 [==============================] - 1s 10us/step - loss: 0.0429 - acc: 0.7971 - val_loss: 0.0418 - val_acc: 0.8116
Epoch 122/200
60000/60000 [==============================] - 1s 10us/step - loss: 0.0426 - acc: 0.7990 - val_loss: 0.0415 - val_acc: 0.8135
Epoch 123/200
60000/60000 [==============================] - 1s 10us/step - loss: 0.0423 - acc: 0.8007 - val_loss: 0.0412 - val_acc: 0.8143
Epoch 124/200
60000/60000 [==============================] - 1s 10us/step - loss: 0.0420 - acc: 0.8025 - val_loss: 0.0409 - val_acc: 0.8155
Epoch 125/200
60000/6

60000/60000 [==============================] - 1s 10us/step - loss: 0.0309 - acc: 0.8506 - val_loss: 0.0298 - val_acc: 0.8600
Epoch 177/200
60000/60000 [==============================] - 1s 10us/step - loss: 0.0308 - acc: 0.8510 - val_loss: 0.0297 - val_acc: 0.8602
Epoch 178/200
60000/60000 [==============================] - 1s 10us/step - loss: 0.0306 - acc: 0.8512 - val_loss: 0.0295 - val_acc: 0.8609
Epoch 179/200
60000/60000 [==============================] - 1s 10us/step - loss: 0.0305 - acc: 0.8517 - val_loss: 0.0294 - val_acc: 0.8615
Epoch 180/200
60000/60000 [==============================] - 1s 10us/step - loss: 0.0303 - acc: 0.8524 - val_loss: 0.0292 - val_acc: 0.8622
Epoch 181/200
60000/60000 [==============================] - 1s 10us/step - loss: 0.0302 - acc: 0.8527 - val_loss: 0.0291 - val_acc: 0.8626
Epoch 182/200
60000/60000 [==============================] - 1s 10us/step - loss: 0.0301 - acc: 0.8531 - val_loss: 0.0290 - val_acc: 0.8628
Epoch 183/200
60000/60000 [=======

In [22]:
model.evaluate(X_test, y_test)

10000/10000 [==============================] - 0s 11us/step


[0.026778634649515153, 0.8699]