# Shallow Neural Network in Keras

Build a shallow neural network to classify MNIST digits

#### Load dependencies

In [1]:
import keras
from keras.datasets import mnist
from keras.models import Sequential
from keras.layers import Dense
from keras.optimizers import SGD

Using TensorFlow backend.


#### Load data

In [2]:
(X_train, y_train), (X_test, y_test) = mnist.load_data()

11493376/11490434 [==============================] - 0s 0us/step


In [3]:
X_train.shape

(60000, 28, 28)

In [4]:
y_train.shape

(60000,)

In [5]:
y_train[0:10]

array([5, 0, 4, 1, 9, 2, 1, 3, 1, 4], dtype=uint8)

In [6]:
X_test.shape

(10000, 28, 28)

In [7]:
X_test[0]

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  

In [8]:
y_test.shape

(10000,)

In [9]:
y_test[0]

7

#### Preprocess data

In [10]:
X_train = X_train.reshape(60000, 784).astype('float32')
X_test = X_test.reshape(10000, 784).astype('float32')

In [11]:
X_train /= 255
X_test /= 255

In [12]:
X_test[0]

array([0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.     

In [13]:
n_classes = 10
y_train = keras.utils.to_categorical(y_train, n_classes)
y_test = keras.utils.to_categorical(y_test, n_classes)

In [14]:
y_test[0]

array([0., 0., 0., 0., 0., 0., 0., 1., 0., 0.], dtype=float32)

#### Design neural network architecture

In [15]:
model = Sequential()
model.add(Dense(64, activation='sigmoid', input_shape=(784,)))
model.add(Dense(10, activation='softmax'))

In [16]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 64)                50240     
_________________________________________________________________
dense_2 (Dense)              (None, 10)                650       
Total params: 50,890
Trainable params: 50,890
Non-trainable params: 0
_________________________________________________________________


In [17]:
(64*784)

50176

In [18]:
(64*784)+64

50240

In [19]:
(10*64)+10

650

#### Configure model

In [20]:
model.compile(loss='mean_squared_error', optimizer=SGD(lr=0.01), metrics=['accuracy'])

#### Train!

In [21]:
model.fit(X_train, y_train, batch_size=128, epochs=200, verbose=1, validation_data=(X_test, y_test))

Train on 60000 samples, validate on 10000 samples
Epoch 1/200
60000/60000 [==============================] - 1s 11us/step - loss: 0.0939 - acc: 0.1061 - val_loss: 0.0930 - val_acc: 0.1223
Epoch 2/200
60000/60000 [==============================] - 1s 10us/step - loss: 0.0924 - acc: 0.1364 - val_loss: 0.0920 - val_acc: 0.1468
Epoch 3/200
60000/60000 [==============================] - 1s 10us/step - loss: 0.0916 - acc: 0.1511 - val_loss: 0.0913 - val_acc: 0.1550
Epoch 4/200
60000/60000 [==============================] - 1s 10us/step - loss: 0.0910 - acc: 0.1580 - val_loss: 0.0908 - val_acc: 0.1590
Epoch 5/200
60000/60000 [==============================] - 1s 10us/step - loss: 0.0905 - acc: 0.1643 - val_loss: 0.0903 - val_acc: 0.1654
Epoch 6/200
60000/60000 [==============================] - 1s 10us/step - loss: 0.0900 - acc: 0.1714 - val_loss: 0.0898 - val_acc: 0.1707
Epoch 7/200
60000/60000 [==============================] - 1s 10us/step - loss: 0.0896 - acc: 0.1778 - val_loss: 0.0894 - 

60000/60000 [==============================] - 1s 10us/step - loss: 0.0686 - acc: 0.5640 - val_loss: 0.0680 - val_acc: 0.5742
Epoch 60/200
60000/60000 [==============================] - 1s 10us/step - loss: 0.0681 - acc: 0.5675 - val_loss: 0.0675 - val_acc: 0.5775
Epoch 61/200
60000/60000 [==============================] - 1s 10us/step - loss: 0.0676 - acc: 0.5707 - val_loss: 0.0670 - val_acc: 0.5803
Epoch 62/200
60000/60000 [==============================] - 1s 10us/step - loss: 0.0672 - acc: 0.5737 - val_loss: 0.0665 - val_acc: 0.5839
Epoch 63/200
60000/60000 [==============================] - 1s 10us/step - loss: 0.0667 - acc: 0.5762 - val_loss: 0.0661 - val_acc: 0.5877
Epoch 64/200
60000/60000 [==============================] - 1s 10us/step - loss: 0.0662 - acc: 0.5799 - val_loss: 0.0656 - val_acc: 0.5905
Epoch 65/200
60000/60000 [==============================] - 1s 10us/step - loss: 0.0658 - acc: 0.5826 - val_loss: 0.0651 - val_acc: 0.5934
Epoch 66/200
60000/60000 [==============

Epoch 118/200
60000/60000 [==============================] - 1s 10us/step - loss: 0.0453 - acc: 0.7438 - val_loss: 0.0445 - val_acc: 0.7517
Epoch 119/200
60000/60000 [==============================] - 1s 10us/step - loss: 0.0450 - acc: 0.7463 - val_loss: 0.0442 - val_acc: 0.7541
Epoch 120/200
60000/60000 [==============================] - 1s 9us/step - loss: 0.0447 - acc: 0.7482 - val_loss: 0.0439 - val_acc: 0.7569
Epoch 121/200
60000/60000 [==============================] - 1s 10us/step - loss: 0.0444 - acc: 0.7507 - val_loss: 0.0436 - val_acc: 0.7589
Epoch 122/200
60000/60000 [==============================] - 1s 10us/step - loss: 0.0442 - acc: 0.7524 - val_loss: 0.0434 - val_acc: 0.7613
Epoch 123/200
60000/60000 [==============================] - 1s 10us/step - loss: 0.0439 - acc: 0.7539 - val_loss: 0.0431 - val_acc: 0.7632
Epoch 124/200
60000/60000 [==============================] - 1s 10us/step - loss: 0.0436 - acc: 0.7560 - val_loss: 0.0428 - val_acc: 0.7648
Epoch 125/200
60000/6

60000/60000 [==============================] - 1s 10us/step - loss: 0.0325 - acc: 0.8414 - val_loss: 0.0316 - val_acc: 0.8488
Epoch 177/200
60000/60000 [==============================] - 1s 10us/step - loss: 0.0324 - acc: 0.8425 - val_loss: 0.0314 - val_acc: 0.8505
Epoch 178/200
60000/60000 [==============================] - 1s 10us/step - loss: 0.0322 - acc: 0.8432 - val_loss: 0.0313 - val_acc: 0.8514
Epoch 179/200
60000/60000 [==============================] - 1s 10us/step - loss: 0.0321 - acc: 0.8443 - val_loss: 0.0311 - val_acc: 0.8524
Epoch 180/200
60000/60000 [==============================] - 1s 10us/step - loss: 0.0319 - acc: 0.8450 - val_loss: 0.0310 - val_acc: 0.8536
Epoch 181/200
60000/60000 [==============================] - 1s 10us/step - loss: 0.0318 - acc: 0.8458 - val_loss: 0.0308 - val_acc: 0.8541
Epoch 182/200
60000/60000 [==============================] - 1s 10us/step - loss: 0.0316 - acc: 0.8467 - val_loss: 0.0307 - val_acc: 0.8549
Epoch 183/200
60000/60000 [=======

In [22]:
model.evaluate(X_test, y_test)

10000/10000 [==============================] - 0s 11us/step


[0.02820772794485092, 0.8654]